[package]
name = "otlp-logs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.14", features = ["tls-native-roots", "gzip"] }
opentelemetry = "0.33"
opentelemetry_sdk = { version = "0.33", features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { version = "0.33", features = ["grpc-tonic", "gzip-tonic", "tls-ring", "tls-roots", "logs"] }
opentelemetry-resource-detectors = "0.13"
opentelemetry-appender-tracing = "0.33"
tracing = { version = ">=0.1.40", features = ["std"]}
tracing-subscriber = { version = "0.3", features = ["env-filter","registry", "std", "fmt"] }
